name: ElytraTournament
version: 1.0
main: net.elytrapvp.elytratournament.ElytraTournament
authors: [ ElytraPvP ]
description: Tournament plugin for ElytraPvP
website: http://www.elytrapvp.net

softdepend:
  - PlaceholderAPI

commands:
  addtitle:
    description: Adds a title to a player.
  create:
    description: Create a tournament
  start:
    description: Start a tournament
  cancel:
    description: Cancel a tournmanet
  bracket:
    description: Get the current bracket.
    aliases: [matches]
  ping:
    description: View a player's ping.